linters:
  Indentation:
    exclude:
      - 'src/assets/css/vendors/**'
    allow_non_nested_indentation: true

  NestingDepth:
    max_depth: 4

  # This is already done automatically:
  # VendorPrefix:
    # excluded_identifiers: [appearance]
